// Jenkinsfile for NationalParks
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"

    // Your Pipeline Code goes here. Make sure to use the ${GUID} and ${CLUSTER} parameters where appropriate
    // You need to build the application in directory `Nationalparks`.
    // Also copy "../nexus_settings.xml" to your build directory
    // and replace 'GUID' in the file with your ${GUID} to point to >your< Nexus instance
    def projectFolder="./Nationalparks"
    def name="nationalparks"
    
    stage("Build"){
      checkout scm
      sh "mvn -s nexus_settings.xml -f ${projectFolder} clean package -DskipTests=true"
    }
    def jarPath="${projectFolder}/target/nationalparks.jar"
    def pomPath="${projectFolder}/pom.xml"
    def groupId    = getGroupIdFromPom(pomPath)
    def artifactId = getArtifactIdFromPom(pomPath)
    def version    = getVersionFromPom(pomPath)
    def devTag  = "${version}-${BUILD_NUMBER}"
    def prodTag = "${version}"  
    stage("Deploy Dev"){
      sh "oc start-build ${name} --from-file=${jarPath} -F -n kxiang-parks-dev"
      sh "oc tag kxiang-parks-dev/${name}:latest kxiang-parks-dev/${name}:${devTag} -n kxiang-parks-dev"
      sh "oc set image dc/${name} ${name}=${name}:${devTag} --source=istag -n kxiang-parks-dev"
      sh "oc rollout latest ${name} -n kxiang-parks-dev"
    }
     def curTarget 
     def destTarget
    stage("Deploy Prod (B/G)"){
      echo "Detecting current target"
      curTarget = sh returnStdout: true, script:"oc get svc/${name} -n kxiang-parks-prod --template=\"{{.spec.selector.deploymentconfig}}\""
      echo "Current pointing target: ${curTarget}"
      destTarget= curTarget.contains("blue")?"${name}-green":"${name}-blue"
      echo "Deploy to target: ${destTarget}"
      sh "oc tag kxiang-parks-dev/${name}:${devTag} kxiang-parks-prod/${name}:${prodTag} -n kxiang-parks-prod"
      sh "oc set image dc/${destTarget} ${destTarget}=${name}:${prodTag} --source=istag -n kxiang-parks-prod"
      sh "oc rollout latest ${destTarget} -n kxiang-parks-prod"
    }
    stage("Swap B/G deployment"){
      sh "oc patch svc/${name} -n kxiang-parks-prod -p '{\"spec\":{\"selector\":{\"deploymentconfig\":\"${destTarget}\"}}}' "
    }

  }
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
